const IMAGES = {
    coloredLogo : new URL('./svg/colored-logo.svg', import.meta.url).href,
    authBanner : new URL('./svg/auth-banner.svg', import.meta.url).href,
    Bicon : new URL('./svg/icons/b-icon.svg', import.meta.url).href,
    FaceIcon : new URL('./svg/icons/facebook-icon.svg', import.meta.url).href,
    InstagramIcon : new URL('./svg/icons/instagram-icon.svg', import.meta.url).href,
    LinkedinIcon : new URL('./svg/icons/linkedin-icon.svg', import.meta.url).href,
    PhoneIcon : new URL('./svg/icons/phone-icon.svg', import.meta.url).href,
    Xicon : new URL('./svg/icons/x-icon.svg', import.meta.url).href,
    userIcon : new URL('./svg/user-icon.svg', import.meta.url).href,
    cartIcon : new URL('./svg/cart-icon.svg', import.meta.url).href,
    favIcon : new URL('./svg/fav-icon.svg', import.meta.url).href,
    book_1 : new URL('./png/books/book1.png', import.meta.url).href,
    book_2 : new URL('./png/books/book2.png', import.meta.url).href,
    book_3 : new URL('./png/books/book3.png', import.meta.url).href,
    book_4 : new URL('./svg/books/book-4.svg', import.meta.url).href,
    featured_book : new URL('./svg/books/featured-book.svg', import.meta.url).href,
    rightArrow : new URL('./svg/right-arrow.svg', import.meta.url).href,
    orangeRightArrow : new URL('./svg/orange-right-arrow.svg', import.meta.url).href,
    orangeLeftArrow : new URL('./svg/orange-left-arrow.svg', import.meta.url).href,
    footer_logo : new URL('./svg/footer-logo.svg', import.meta.url).href,

    footer_facebook : new URL('./svg/icons/footer/facebook.svg', import.meta.url).href,
    footer_linkidin : new URL('./svg/icons/footer/linkidin.svg', import.meta.url).href,
    footer_twitter : new URL('./svg/icons/footer/twitter.svg', import.meta.url).href,
    footer_youtube : new URL('./svg/icons/footer/youtube.svg', import.meta.url).href,
    grid_icon : new URL('./svg/icons/grid-icon.svg', import.meta.url).href,
    list_icon : new URL('./svg/icons/list-icon.svg', import.meta.url).href,
    shopping_cart : new URL('./svg/shopping-cart.svg', import.meta.url).href,
    empty : new URL('./svg/empty.svg', import.meta.url).href,

    category_1 : new URL('./png/category-1.png', import.meta.url).href,
    category_2 : new URL('./png/category-2.png', import.meta.url).href,
    category_3 : new URL('./png/category-3.png', import.meta.url).href,
    bookSlider : new URL('./png/slider-book.png', import.meta.url).href,
    featured_book_png : new URL('./png/featured-book.png', import.meta.url).href,
    featured_book2_png : new URL('./png/featured-book-2.png', import.meta.url).href,
    featured_book3_png : new URL('./png/featured-book-3.png', import.meta.url).href,
    deals_book_1_png : new URL('./png/deals-book-1.png', import.meta.url).href,

    latest_book_1 : new URL('./png/latest/latest-1.png', import.meta.url).href,
    latest_book_2 : new URL('./png/latest/latest-2.png', import.meta.url).href,
    latest_book_3 : new URL('./png/latest/latest-3.png', import.meta.url).href,

    loader_gif : new URL('./png/loader.gif', import.meta.url).href,
    circle_preloader : new URL('./png/circle-preloader.gif', import.meta.url).href,
}

export default IMAGES